#index:
#    path: /
#    controller: App\Controller\DefaultController::index

seller:
    path: /api/seller
    # the controller value has the format 'controller_class::method_name'
    controller: App\Controller\SellerController::getSellersFromUrl
